### ISSUE TITLE
Train Prefab getting errors

### ISSUE THREAD

**Issue by turnercore** [ltsLumina/FG-GP-Team1#14]
I'm getting script errors from these on the train prefab, says my branch is up to date with main

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/01f0dec9-97e9-491e-81b1-b5786d840925)

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/81bf7be8-7b89-4bc0-85fe-85a173d14d48)

**Comment by ltsLumina** [comment]
I'll take a look. I'm pretty sure I know what the issue is.
Is this on the Design branch?

**Comment by turnercore** [comment]
It was on Alpha I think, maybe Design, and I spun off turner branch and merged all the other branches into me. And it's for sure on that branch (where I'm working now)
