### ISSUE TITLE
Possible memory Leak

### ISSUE THREAD

**Issue by turnercore** [ltsLumina/FG-GP-Team1#6]
![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/20b439c6-a5f8-43ef-9dcb-1223ee6e64d0)

I just have PlayerMovementPlayground scene open and nothing else. Global Illumination Preprocessing is happening (and taking forever). Not sure if this is a real issue or not, but thought I'd post it just in case.

**Comment by ltsLumina** [comment]
GI Preprocessing needs to bake once per scene and will take forever; we're baking all the lighting. Settings aren't final so its taking longer than it should. Let it run-through once properly and restart Unity, then there shouldn't be an issue. 
On another note, depending on the version of the project you're currently on, there is a known leak with the procedural wall. This is being actively worked on.
